spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/exemplo
    password:
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root