server:
  port: 8081
spring:
  application:
    name: "exemplo"
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/exemplo
    password:
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop